### ISSUE TITLE
Any updates on the Pipewire situation?

### ISSUE THREAD

**Issue by AudioBabbL** [chmaha/DebianProAudio#3]
Hi, I've installed Debian Bookworm (Edu version) with the netinstaller. I have cinnamon desktop.

I've followed your guide, but didn't revert to JACK/Pulseaudio. Must say, everything seems to be running 100%.

pipewire --version shows:

```
pipewire
Compiled with libpipewire 0.3.65
Linked with libpipewire 0.3.65

```

Are you still of the opinion that Pipewire is 'not ready for prime-time'?

I've followed the official build instructions, and after install, Pipewire version is still as above.

Pipewire docs seem to suggest that there's no need to build from source on Debian 12.

Is it possible that Debian netinstaller already got the most recent updated packages?

**Comment by chmaha** [comment]
On Fedora, I'm up to 1.2.7. I suspect you are not using the version you built. 0.3.65 still has issues for certain things. Install a later version from backports if you must. Don't just take my word for it - see what Robin Gareus, one of the Ardour devs, has to say: https://ubuntustudio.org/switching-audio-setup/. Debian 12 hasn't updated the pipewire version since it was released (unless as I say you want to install from backports). Therefore, I'm still of the opinion it is best to wait for Debian 13 to switch to pipewire for professional audio. My advice from 2023 still stands in other words ;) All other faster moving distros are probably good at this point.

**Comment by AudioBabbL** [comment]
If only I could get the official build to work, but I think it's a bit beyond me! I may look into the backport route... but since I'm not really heavily invested in Debian, might be best to just install Fedora. According to what I can see online, Fedora 41 has pipewire 1.2.3. Seems only Rawhide version has 1.2.7 at the moment... I think Ubuntu Studio and AV Linux are up to 1.0.0

[edit] after adding: ```deb http://deb.debian.org/debian bookworm-backports main```
to: /etc/apt/sources.list.d/debian-12-backports.list

I actually just did 'sudo apt install -t bookworm-backports pipewire', and that appears to have pulled all the related packages (1.2.5 is latest on bookworm backports)
```
The following additional packages will be installed:
  libpipewire-0.3-0 libpipewire-0.3-common libpipewire-0.3-modules
  libspa-0.2-bluetooth libspa-0.2-modules pipewire-alsa pipewire-audio
  pipewire-audio-client-libraries pipewire-bin pipewire-jack pipewire-pulse
The following packages will be upgraded:
  libpipewire-0.3-0 libpipewire-0.3-common libpipewire-0.3-modules
  libspa-0.2-bluetooth libspa-0.2-modules pipewire pipewire-alsa
  pipewire-audio pipewire-audio-client-libraries pipewire-bin pipewire-jack
  pipewire-pulse
```
so now $ pipewire --version gives:
```
pipewire
Compiled with libpipewire 1.2.5
Linked with libpipewire 1.2.5
```

not sure if I need to also update wireplumber to backport version, or whether I might have missed anything?

**Comment by chmaha** [comment]
Yes, you probably need to upgrade all related packages including the latest wireplumber you can find. This is why I avoided backports as it is quite messy to maintain. As for Fedora, I'm on F41 and not rawhide. Fedora has a more relaxed policy of minor package version updates compared to Debian. Here's the update info: https://bodhi.fedoraproject.org/updates/FEDORA-2024-18bf137a0c. As in, it is in the official Fedora 41 updates repository and a completely automatic update when you run `sudo dnf up`.

The other thing to note is that my guides are specifically for "professional" audio. For many people who might be using a DAW as part of a bedroom hobby, I'm sure Debian 12's pipewire version might get them by (or at least because most people are not aware of the potential issues). But, yes, I'm really catering for people trying to make money by running their audio projects on Linux, involved in live public performance, or at the very least running in a way that gives them a like-for-like replacement for what they had with JACK. Even with the latest more robust pipewire, I'm not sure that is true. But, in any case, my guides are here to ensure that the system is stable and performing as well as possible via at least a handful of minor tweaks and more as necessary (system dependent).

**Comment by chmaha** [comment]
BTW, I am a regular user of the REAPER forums and am the creator of ReaClassical (http://reaclassical.org and https://forum.cockos.com/showthread.php?t=265145). For various reasons, many months ago, I chose to no longer participate in the Linux subforum.
